version: "2"
plugins:
  checkstyle:
    enabled: true
  codenarc:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  pmd:
    enabled: true
  shellcheck:
    enabled: true
  sonar-java:
    enabled: true
exclude_patterns:
  - "AlmostSecureApplet/ext/"
  - "AlmostSecureApplet/!uploader/"
  - "JCMathLib-master/"
  - "SimpleAPDU/lib/"
  - "SimpleAPDU/nbproject/"
  - "SimpleAPDU/dist/"
  - "SimpleAPDU/src/cardTools/"
